backend:
  name: git-gateway
  branch: main
  identity_url: https://portifoliola.netlify.app/.netlify/identity
  site_domain: portifoliola.netlify.app
  

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.html"
        label: "Página Inicial"
        name: "home"
        fields:
          - { label: "Conteúdo", name: "body", widget: "markdown" }
